const ADD_HOTELS = 'ADD_HOTELS';
const ADD_SINGLE_HOTEL = 'ADD_SINGLE_HOTEL';
const LOGIN = 'LOGIN';
const SIGN_OUT = 'SIGN_OUT';
const LOGIN_ERROR = 'LOGIN_ERROR';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const CLEAR_ERROR = 'CLEAR_ERROR';

const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';
const CLEAR_CART = 'CLEAR_CART';
const LOADING = 'LOADING';

const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
const CLEAR_ORDER_DETAILS = 'CLEAR_ORDER_DETAILS';

export {
  ADD_HOTELS,
  ADD_TO_CART,
  LOGIN,
  LOGIN_ERROR,
  SIGNUP_ERROR,
  CLEAR_ERROR,
  ADD_SINGLE_HOTEL,
  REMOVE_FROM_CART,
  SET_SELECTED_SERVICE,
  CLEAR_CART,
  SIGN_OUT,
  LOADING,
  GET_ORDER_DETAILS,
  CLEAR_ORDER_DETAILS,
};
